version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "ipr-govNotify-stub"
s3_prefix = "ipr-govNotify-stub"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CodeSigningConfigArn=\"none\" Environment=\"dev\" PermissionsBoundary=\"none\" SecretPrefix=\"none\" VpcStackName=\"vpc-cri\""
image_repositories = []
