export const constants = {
	API_TEST_GOV_NOTIFY_SQS_QUEUE: process.env.API_TEST_GOV_NOTIFY_SQS_QUEUE,
	API_TEST_SQS_TXMA_CONSUMER_QUEUE: process.env.API_TEST_SQS_TXMA_CONSUMER_QUEUE,
	API_TEST_SESSION_EVENTS_TABLE: process.env.API_TEST_SESSION_EVENTS_TABLE,
	DEV_IPR_TEST_HARNESS_URL: process.env.DEV_IPR_TEST_HARNESS_URL,
	DEV_IPR_API_URL: process.env.DEV_IPR_API_URL,
	API_TEST_EMAIL_ADDRESS: "zac.mohamoud@digital.cabinet-office.gov.uk",
};
