export enum ServicesEnum {
	GOV_NOTIFY_SERVICE = "IPR_GOV_NOTIFY_SERVICE",
	STREAM_PROCESSOR_SERVICE = "IPR_STREAM_PROCESSOR_SERVICE",
	POST_EVENT_SERVICE = "POST_EVENT_SERVICE",
	GET_SESSION_EVENT_DATA_SERVICE = "GET_SESSION_EVENT_DATA_SERVICE",
	NA = "NA",
}
