openapi: 3.0.2
info:
  title:
    Fn::Sub: "${AWS::StackName} - Oidc Stub Service"
  version: 1.0.0

tags:
  - name: Public Endpoints
    description: Endpoints accessible by the public domain

paths:
  /:
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:OidcProvider-Stub-${AWS::StackName}:live/invocations
        type: "aws_proxy"   

  /{proxy+}:
    x-amazon-apigateway-any-method:
      parameters:
      - name: proxy
        in: path
        required: true
        schema:
          type: string
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:OidcProvider-Stub-${AWS::StackName}:live/invocations
        type: "aws_proxy"     
