AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Digital Identity IPR OIDC Stub"

Parameters:
  KmsPendingWindowInDays:
    Type: Number
    Description: Number of days to retain KMS in pending deletion state when deleted
    Default: 30
  CodeSigningConfigArn:
    Type: String
    Default: "none"
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
  Environment:
    Description: "The environment type"
    Type: "String"
    AllowedValues:
      - "dev"
      - "build"

    ConstraintDescription: Ensure environment variable is set to one of dev, build.
  PermissionsBoundary:
    Description: "The ARN of the permissions boundary to apply when creating IAM roles"
    Type: String
    Default: "none"
  VpcStackName:
    Type: String
    Default: "vpc-cri"
    Description: The name of the VPC stack deployed.

Mappings:
  EnvironmentConfiguration: # This is where you store per-environment settings.
    dev:
      logretentionindays: 3
      apiTracingEnabled: true
    build:
      logretentionindays: 3
      apiTracingEnabled: true

  EnvironmentVariables: # This is all the environment specific environment variables that don't belong in globals.
    dev:
      OIDCSTUBDNS: "oidcstub.return.dev.account.gov.uk"
      JWKSURI: "https://ipvreturn-api.return.dev.account.gov.uk"
      OIDCURL: "https://ipr-oidc-stub-oidcstub.return.dev.account.gov.uk/" 
    build:
      OIDCSTUBDNS: "oidcstub.return.build.account.gov.uk"
      JWKSURI: "https://ipvreturn-api.return.dev.account.gov.uk"
      OIDCURL: "https://ipr-oidc-stub-oidcstub.return.build.account.gov.uk/" 

Conditions:
  CreateDevResources: !Equals
    - !Ref Environment
    - dev
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"

Globals:
  Api:
    BinaryMediaTypes:
      - '*/*'
  Function:
    Runtime: nodejs18.x
    VpcConfig:
      SecurityGroupIds:
        - !GetAtt LambdaEgressSecurityGroup.GroupId
      SubnetIds:
        - Fn::ImportValue:
            "Fn::Sub": "${VpcStackName}-ProtectedSubnetIdA"
        - Fn::ImportValue:
            "Fn::Sub": "${VpcStackName}-ProtectedSubnetIdB"
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    Timeout: 30 # seconds
    Tracing: Active
    MemorySize: 1024
    Architectures:
      - arm64
    Environment:
      Variables:
        # These should always be alphabetically organised.
        AWS_STACK_NAME: !Sub ${AWS::StackName} # The AWS Stack Name, as passed into the template.
        POWERTOOLS_LOG_LEVEL: INFO # The LogLevel for the AWS PowerTools LogHelper
        POWERTOOLS_METRICS_NAMESPACE: IPR-CRI # The Metric Namespace for the AWS PowerTools MetricHelper
    AutoPublishAlias: live

Resources:
  LambdaEgressSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: >-
        Permits outbound on port 443 from within the VPC to the internet.
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow to the wider internet on port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      VpcId:
        Fn::ImportValue: !Sub "${VpcStackName}-VpcId"
  
  ## OIDC Provider as IAM entity- Local deployment
  OIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - !Sub "{{resolve:ssm:/${Environment}/ipvreturn/CLIENT_ID}}"
      ThumbprintList:
        - !Sub "{{resolve:ssm:/${Environment}/ipvreturn/OIDC_THUMBPRINT}}"
      Url: !FindInMap [ EnvironmentVariables, !Ref Environment, OIDCURL ]

  ### Start of API Gateway definition.

  MockOidcRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      OpenApiVersion: 3.0.2
      AccessLogSetting:
        Format: "$context.requestId $context.httpMethod $context.path"
        DestinationArn: !GetAtt MockOidcAPIGatewayAccessLogGroup.Arn
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        ## workaround as https://github.com/aws/serverless-application-model/blob/14d0563e5f48adbb0d1ff1c807ca3eeb17adc3d8/samtranslator/swagger/swagger.py#L65
        ## won't allow BinaryMediaTypes with external openapi sppec file
        openapi: '3.0.2'
        paths:
          /myMethod:
            post:
              produces:
                - "application/json"
              responses: { }

        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: './oidc-spec.yaml'

      TracingEnabled: true
      Tags:
        Product: GOV.UK Sign In
        System: OidcMock
        Environment: !Ref Environment
        Service: backend
        Name: MockOidcRestApi
        Source: oidc

  MockOidcRestApiUsagePlan:
    DependsOn:
      - "MockOidcRestApi"
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref MockOidcRestApi
          Stage: !Ref Environment
      Quota:
        Limit: 250000
        Period: DAY
      Throttle:
        BurstLimit: 3000 # requests the API can handle concurrently
        RateLimit: 50 # allowed requests per second

  MockOidcAPIGatewayAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays:
        !FindInMap [
          EnvironmentConfiguration,
          !Ref Environment,
          logretentionindays,
        ]

      Tags:
        - Key: Product
          Value: GOV.UK Sign In
        - Key: System
          Value: Oidc
        - Key: Environment
          Value: Demo
        - Key: Service
          Value: backend
        - Key: Name
          Value: APIGatewayAccessLogGroup


  ### End of API Gateway definition.

  ### Function Definition
  ## OIDC
  MockOidcFunction:
    Type: AWS::Serverless::Function
    DependsOn: MockOidcFunctionLogGroup
    Properties:
      FunctionName: !Sub "Oidc-Stub-${AWS::StackName}"
      Handler: MockOidcHandler.lambdaHandler
      CodeUri: ./src/
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: MockOidcHandler
          SIGNING_KEY: !Ref OIDCStubKMSSigningKey
          JWKS_URI: !FindInMap [EnvironmentVariables, !Ref Environment, JWKSURI]
          OIDC_URL: !FindInMap [EnvironmentVariables, !Ref Environment, OIDCURL]

      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - Statement:
            - Sid: KMSSignPolicy
              Effect: Allow
              Action:
                - kms:Sign
              Resource:
                - !GetAtt OIDCStubKMSSigningKey.Arn
      Events:
        token:
          Type: Api
          Properties:
            Path: /token
            Method: post
            RestApiId: !Ref MockOidcRestApi
        openidConfiguration:
          Type: Api
          Properties:
            Path: /.well-known/openid-configuration
            Method: get
            RestApiId: !Ref MockOidcRestApi
        authorize:
          Type: Api
          Properties:
            Path: /authorize
            Method: get
            RestApiId: !Ref MockOidcRestApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - MockOidcHandler.ts

  MockOidcFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/Oidc-${AWS::StackName}"
      RetentionInDays: !FindInMap [ EnvironmentConfiguration, !Ref Environment, logretentionindays ]

  MockOidcFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MockOidcFunction
      Principal: apigateway.amazonaws.com
  
  JwksFunction:
    DependsOn:
      - JwksFunctionLogGroup
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "OIDCStubJWKS-${AWS::StackName}"
      Handler: JsonWebKeys.handler
      CodeUri: ./src/
      Environment:
        Variables:
          SIGNING_KEY: !Ref OIDCStubKMSSigningKey
      Policies:
        - Statement:
            - Sid: KMSSignPolicy
              Effect: Allow
              Action:
                - kms:GetPublicKey
              Resource:
                - !GetAtt OIDCStubKMSSigningKey.Arn
      Events:
        token:
          Type: Api
          Properties:
            Path: /.well-known/jwks.json
            Method: get
            RestApiId: !Ref MockOidcRestApi
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - JsonWebKeys.ts

  JwksFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt JwksFunction.Arn
      Principal: apigateway.amazonaws.com

  JwksFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30
      LogGroupName: !Sub "/aws/lambda/OIDCStubJWKS-${AWS::StackName}"
  
  OIDCStubKMSSigningKey:
    Type: AWS::KMS::Key
    Properties:
      Description: A KMS Key for testing signing KMS integration in the development account.
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource:
              - "*"
      KeySpec: RSA_2048
      KeyUsage: SIGN_VERIFY
      MultiRegion: false
      PendingWindowInDays: 7
      Tags:
        - Key: KeyType
          Value: Test Signing Key
        - Key: Environment
          Value: !Sub ${Environment}

  MockOidcApiGatewayCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !If
        - CreateDevResources
        - !Sub
          - "${AWS::StackName}-${OIDCSTUBDNS}"
          - OIDCSTUBDNS:
              !FindInMap [ EnvironmentVariables, !Ref Environment, OIDCSTUBDNS ]
        - !FindInMap [ EnvironmentVariables, !Ref Environment, OIDCSTUBDNS ]
      DomainNameConfigurations:
        - CertificateArn: !Sub "{{resolve:ssm:/${Environment}/Platform/ACM/PrimaryZoneWildcardCertificateARN}}"
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  MockOidcApiDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref MockOidcApiGatewayCustomDomain
      Type: A
      HostedZoneId: !Sub "{{resolve:ssm:/${Environment}/Platform/Route53/PrimaryZoneID}}"
      AliasTarget:
        DNSName: !GetAtt MockOidcApiGatewayCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt MockOidcApiGatewayCustomDomain.RegionalHostedZoneId
        EvaluateTargetHealth: false

  #Base Path Mapping
  MockOidcApiBasePathMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    Properties:
      DomainName: !Ref MockOidcApiGatewayCustomDomain
      RestApiId: !Ref MockOidcRestApi

      # workaround for sam bug - see https://github.com/aws/serverless-application-model/issues/192#issuecomment-520893111
      # noinspection YamlUnresolvedReferences
      Stage: !Ref MockOidcRestApi.Stage

Outputs:
  MockOidcApiGatewayId:
    Description: "API GatewayID of the Oidc API"
    Value: !Sub "${MockOidcRestApi}"
    Export:
      Name: !Sub ${AWS::StackName}-MockOidcApiGatewayId
